version: "3.9"
   
services:    
  web:
    build: .
    command: gunicorn appointment_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000

  nginx:
    build: ./nginx
    links:
      - web:web
    ports:
      - 80:80
    depends_on:
      - web
